apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: ecommerce
data:
  MONGODB_URI: "mongodb://mongo:27017"
  REDIS_URL: "redis://redis:6379"
  
  # Service URLs
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  CART_SERVICE_URL: "http://cart-service:3003"
  REVIEW_SERVICE_URL: "http://review-service:3004"
  PAYMENT_SERVICE_URL: "http://payment-service:3005"
  ORDER_SERVICE_URL: "http://order-service:8080"
  
  # API Gateway
  API_GATEWAY_URL: "http://api-gateway:8000"
