name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push auth-service
        run: |
          docker build -t darwinvinoth/vinothsre/auth-service:latest ./auth-service
          docker push darwinvinoth/vinothsre/auth-service:latest

      - name: Build & Push order-service
        run: |
          docker build -t darwinvinoth/vinothsre/order-service:latest ./order-service
          docker push darwinvinoth/vinothsre/order-service:latest

      - name: Build & Push product-service
        run: |
          docker build -t darwinvinoth/vinothsre/product-service:latest ./product-service
          docker push darwinvinoth/vinothsre/product-service:latest


      - name: Build & Push order-service
        run: |
          docker build -t darwinvinoth/vinothsre/cart-service:latest ./cart-service
          docker push darwinvinoth/vinothsre/cart-service:latest 
          
      - name: Build & Push payment-service
        run: |
          docker build -t darwinvinoth/vinothsre/cart-service:latest ./payment-service
          docker push darwinvinoth/vinothsre/payment-service:latest  
          
      - name: Build & Push review-service
        run: |
          docker build -t darwinvinoth/vinothsre/cart-service:latest ./review-service
          docker push darwinvinoth/vinothsre/review-service:latest
          
      - name: Build & Push frontend-service
        run: |
          docker build -t darwinvinoth/vinothsre/frontend-service:latest ./frontend
          docker push darwinvinoth/vinothsre/frontend-service:latest

      - name: Check secrets
        run: |
          echo "Username is set? true
